CREATE TABLE public.countries
(
    alpha2 character varying COLLATE pg_catalog."default" NOT NULL,
    alpha3 character varying COLLATE pg_catalog."default",
    name_ru character varying COLLATE pg_catalog."default",
    name_tj character varying COLLATE pg_catalog."default",
    name_en character varying COLLATE pg_catalog."default",
    iso character varying COLLATE pg_catalog."default",
    CONSTRAINT countries_pkey PRIMARY KEY (alpha2)
)

INSERT INTO public.countries VALUES ('AB', 'ABH', 'Абхазия', 'Абхазия', 'Abkhazia', '895');
INSERT INTO public.countries VALUES ('AU', 'AUS', 'Австралия', 'Австралия', 'Australia', '36');
INSERT INTO public.countries VALUES ('AT', 'AUT', 'Австрия', 'Австрия', 'Austria', '40');
INSERT INTO public.countries VALUES ('AZ', 'AZE', 'Азербайджан', 'Азербайджан', 'Azerbaijan', '31');
INSERT INTO public.countries VALUES ('AL', 'ALB', 'Албания', 'Албания', 'Albania', '8');
INSERT INTO public.countries VALUES ('DZ', 'DZA', 'Алжир', 'Алжир', 'Algeria', '12');
INSERT INTO public.countries VALUES ('AO', 'AGO', 'Ангола', 'Ангола', 'Angola', '24');
INSERT INTO public.countries VALUES ('AD', 'AND', 'Андорра', 'Андорра', 'Andorra', '20');
INSERT INTO public.countries VALUES ('AQ', 'ATA', 'Антарктида', 'Антарктида', 'Antarctica', '10');
INSERT INTO public.countries VALUES ('AR', 'ARG', 'Аргентина', 'Аргентина', 'Argentina', '32');
INSERT INTO public.countries VALUES ('AM', 'ARM', 'Армения', 'Армения', 'Armenia', '51');
INSERT INTO public.countries VALUES ('AF', 'AFG', 'Афганистан', 'Афганистан', 'Afghanistan', '4');
INSERT INTO public.countries VALUES ('BS', 'BHS', 'Багамы', 'Багамы', 'Bahamas', '44');
INSERT INTO public.countries VALUES ('BD', 'BGD', 'Бангладеш', 'Бангладеш', 'Bangladesh', '50');
INSERT INTO public.countries VALUES ('BH', 'BHR', 'Бахрейн', 'Бахрейн', 'Bahrain', '48');
INSERT INTO public.countries VALUES ('BY', 'BLR', 'Беларусь', 'Беларусь', 'Belarus', '112');
INSERT INTO public.countries VALUES ('BE', 'BEL', 'Бельгия', 'Бельгия', 'Belgium', '56');
INSERT INTO public.countries VALUES ('BM', 'BMU', 'Бермуды', 'Бермуды', 'Bermuda', '60');
INSERT INTO public.countries VALUES ('BG', 'BGR', 'Болгария', 'Болгария', 'Bulgaria', '100');
INSERT INTO public.countries VALUES ('BO', 'BOL', 'Боливия', 'Боливия', 'Bolivia', '68');
INSERT INTO public.countries VALUES ('BQ', 'BES', 'Бонайре', 'Бонайре', 'Bonaire', '535');
INSERT INTO public.countries VALUES ('BA', 'BIH', 'Босния и Герцеговина', 'Босния и Герцеговина', 'Bosnia and Herzegovina', '70');
INSERT INTO public.countries VALUES ('BR', 'BRA', 'Бразилия', 'Бразилия', 'Brazil', '76');
INSERT INTO public.countries VALUES ('BF', 'BFA', 'Буркина-Фасо', 'Буркина-Фасо', 'Burkina Faso', '854');
INSERT INTO public.countries VALUES ('HU', 'HUN', 'Венгрия', 'Венгрия', 'Hungary', '348');
INSERT INTO public.countries VALUES ('VE', 'VEN', 'Венесуэла', 'Венесуэла', 'Venezuela', '862');
INSERT INTO public.countries VALUES ('VN', 'VNM', 'Вьетнам', 'Вьетнам', 'Vietnam', '704');
INSERT INTO public.countries VALUES ('GA', 'GAB', 'Габон', 'Габон', 'Gabon', '266');
INSERT INTO public.countries VALUES ('HT', 'HTI', 'Гаити', 'Гаити', 'Haiti', '332');
INSERT INTO public.countries VALUES ('GY', 'GUY', 'Гайана', 'Гайана', 'Guyana', '328');
INSERT INTO public.countries VALUES ('GM', 'GMB', 'Гамбия', 'Гамбия', 'Gambia', '270');
INSERT INTO public.countries VALUES ('GH', 'GHA', 'Гана', 'Гана', 'Ghana', '288');
INSERT INTO public.countries VALUES ('GP', 'GLP', 'Гваделупа', 'Гваделупа', 'Guadeloupe', '312');
INSERT INTO public.countries VALUES ('GT', 'GTM', 'Гватемала', 'Гватемала', 'Guatemala', '320');
INSERT INTO public.countries VALUES ('GN', 'GIN', 'Гвинея', 'Гвинея', 'Guinea', '324');
INSERT INTO public.countries VALUES ('DE', 'DEU', 'Германия', 'Германия', 'Germany', '276');
INSERT INTO public.countries VALUES ('GI', 'GIB', 'Гибралтар', 'Гибралтар', 'Gibraltar', '292');
INSERT INTO public.countries VALUES ('HN', 'HND', 'Гондурас', 'Гондурас', 'Honduras', '340');
INSERT INTO public.countries VALUES ('HK', 'HKG', 'Гонконг', 'Гонконг', 'Hong Kong', '344');
INSERT INTO public.countries VALUES ('GL', 'GRL', 'Гренландия', 'Гренландия', 'Greenland', '304');
INSERT INTO public.countries VALUES ('GR', 'GRC', 'Греция', 'Греция', 'Greece', '300');
INSERT INTO public.countries VALUES ('GE', 'GEO', 'Грузия', 'Грузия', 'Georgia', '268');
INSERT INTO public.countries VALUES ('DK', 'DNK', 'Дания', 'Дания', 'Denmark', '208');
INSERT INTO public.countries VALUES ('DO', 'DOM', 'Доминиканская Республика', 'Доминиканская Республика', 'Dominican Republic', '214');
INSERT INTO public.countries VALUES ('EG', 'EGY', 'Египет', 'Египет', 'Egypt', '818');
INSERT INTO public.countries VALUES ('ZM', 'ZMB', 'Замбия', 'Замбия', 'Zambia', '894');
INSERT INTO public.countries VALUES ('ZW', 'ZWE', 'Зимбабве', 'Зимбабве', 'Zimbabwe', '716');
INSERT INTO public.countries VALUES ('IL', 'ISR', 'Израиль', 'Израиль', 'Israel', '376');
INSERT INTO public.countries VALUES ('IN', 'IND', 'Индия', 'Индия', 'India', '356');
INSERT INTO public.countries VALUES ('ID', 'IDN', 'Индонезия', 'Индонезия', 'Indonesia', '360');
INSERT INTO public.countries VALUES ('JO', 'JOR', 'Иордания', 'Иордания', 'Jordan', '400');
INSERT INTO public.countries VALUES ('IQ', 'IRQ', 'Ирак', 'Ирак', 'Iraq', '368');
INSERT INTO public.countries VALUES ('IR', 'IRN', 'Иран', 'Иран', 'Iran', '364');
INSERT INTO public.countries VALUES ('IE', 'IRL', 'Ирландия', 'Ирландия', 'Ireland', '372');
INSERT INTO public.countries VALUES ('IS', 'ISL', 'Исландия', 'Исландия', 'Iceland', '352');
INSERT INTO public.countries VALUES ('ES', 'ESP', 'Испания', 'Испания', 'Spain', '724');
INSERT INTO public.countries VALUES ('IT', 'ITA', 'Италия', 'Италия', 'Italy', '380');
INSERT INTO public.countries VALUES ('YE', 'YEM', 'Йемен', 'Йемен', 'Yemen', '887');
INSERT INTO public.countries VALUES ('KZ', 'KAZ', 'Казахстан', 'Казахстан', 'Kazakhstan', '398');
INSERT INTO public.countries VALUES ('KH', 'KHM', 'Камбоджа', 'Камбоджа', 'Cambodia', '116');
INSERT INTO public.countries VALUES ('CM', 'CMR', 'Камерун', 'Камерун', 'Cameroon', '120');
INSERT INTO public.countries VALUES ('CA', 'CAN', 'Канада', 'Канада', 'Canada', '124');
INSERT INTO public.countries VALUES ('QA', 'QAT', 'Катар', 'Катар', 'Qatar', '634');
INSERT INTO public.countries VALUES ('KE', 'KEN', 'Кения', 'Кения', 'Kenya', '404');
INSERT INTO public.countries VALUES ('CY', 'CYP', 'Кипр', 'Кипр', 'Cyprus', '196');
INSERT INTO public.countries VALUES ('KG', 'KGZ', 'Киргизия', 'Киргизия', 'Kyrgyzstan', '417');
INSERT INTO public.countries VALUES ('CN', 'CHN', 'Китай', 'Китай', 'China', '156');
INSERT INTO public.countries VALUES ('CO', 'COL', 'Колумбия', 'Колумбия', 'Colombia', '170');
INSERT INTO public.countries VALUES ('CG', 'COG', 'Конго', 'Конго', 'Congo', '178');
INSERT INTO public.countries VALUES ('KR', 'KOR', 'Корея', 'Корея', 'Korea', '410');
INSERT INTO public.countries VALUES ('CR', 'CRI', 'Коста-Рика', 'Коста-Рика', 'Costa Rica', '188');
INSERT INTO public.countries VALUES ('CI', 'CIV', 'Кот д''Ивуар', 'Кот д''Ивуар', 'Cote d''Ivoire', '384');
INSERT INTO public.countries VALUES ('CU', 'CUB', 'Куба', 'Куба', 'Cuba', '192');
INSERT INTO public.countries VALUES ('KW', 'KWT', 'Кувейт', 'Кувейт', 'Kuwait', '414');
INSERT INTO public.countries VALUES ('LA', 'LAO', 'Лаос', 'Лаос', 'Lao', '418');
INSERT INTO public.countries VALUES ('LV', 'LVA', 'Латвия', 'Латвия', 'Latvia', '428');
INSERT INTO public.countries VALUES ('LB', 'LBN', 'Ливан', 'Ливан', 'Lebanon', '422');
INSERT INTO public.countries VALUES ('LY', 'LBY', 'Ливия', 'Ливия', 'Libyan', '434');
INSERT INTO public.countries VALUES ('LR', 'LBR', 'Либерия', 'Либерия', 'Liberia', '430');
INSERT INTO public.countries VALUES ('LI', 'LIE', 'Лихтенштейн', 'Лихтенштейн', 'Liechtenstein', '438');
INSERT INTO public.countries VALUES ('LT', 'LTU', 'Литва', 'Литва', 'Lithuania', '440');
INSERT INTO public.countries VALUES ('LU', 'LUX', 'Люксембург', 'Люксембург', 'Luxembourg', '442');
INSERT INTO public.countries VALUES ('MG', 'MDG', 'Мадагаскар', 'Мадагаскар', 'Madagascar', '450');
INSERT INTO public.countries VALUES ('MY', 'MYS', 'Малайзия', 'Малайзия', 'Malaysia', '458');
INSERT INTO public.countries VALUES ('ML', 'MLI', 'Мали', 'Мали', 'Mali', '466');
INSERT INTO public.countries VALUES ('MV', 'MDV', 'Мальдивы', 'Мальдивы', 'Maldives', '462');
INSERT INTO public.countries VALUES ('MT', 'MLT', 'Мальта', 'Мальта', 'Malta', '470');
INSERT INTO public.countries VALUES ('MA', 'MAR', 'Марокко', 'Марокко', 'Morocco', '504');
INSERT INTO public.countries VALUES ('MX', 'MEX', 'Мексика', 'Мексика', 'Mexico', '484');
INSERT INTO public.countries VALUES ('MZ', 'MOZ', 'Мозамбик', 'Мозамбик', 'Mozambique', '508');
INSERT INTO public.countries VALUES ('MD', 'MDA', 'Молдова', 'Молдова', 'Moldova', '498');
INSERT INTO public.countries VALUES ('MC', 'MCO', 'Монако', 'Монако', 'Monaco', '492');
INSERT INTO public.countries VALUES ('MN', 'MNG', 'Монголия', 'Монголия', 'Mongolia', '496');
INSERT INTO public.countries VALUES ('MM', 'MMR', 'Мьянма', 'Мьянма', 'Burma', '104');
INSERT INTO public.countries VALUES ('NP', 'NPL', 'Непал', 'Непал', 'Nepal', '524');
INSERT INTO public.countries VALUES ('NE', 'NER', 'Нигер', 'Нигер', 'Niger', '562');
INSERT INTO public.countries VALUES ('NG', 'NGA', 'Нигерия', 'Нигерия', 'Nigeria', '566');
INSERT INTO public.countries VALUES ('NL', 'NLD', 'Нидерланды', 'Нидерланды', 'Netherlands', '528');
INSERT INTO public.countries VALUES ('NI', 'NIC', 'Никарагуа', 'Никарагуа', 'Nicaragua', '558');
INSERT INTO public.countries VALUES ('NZ', 'NZL', 'Новая Зеландия', 'Новая Зеландия', 'New Zealand', '554');
INSERT INTO public.countries VALUES ('NO', 'NOR', 'Норвегия', 'Норвегия', 'Norway', '578');
INSERT INTO public.countries VALUES ('AE', 'ARE', 'Объединенные Арабские Эмираты', 'Объединенные Арабские Эмираты', 'United Arab Emirates', '784');
INSERT INTO public.countries VALUES ('OM', 'OMN', 'Оман', 'Оман', 'Oman', '512');
INSERT INTO public.countries VALUES ('PK', 'PAK', 'Пакистан', 'Пакистан', 'Pakistan', '586');
INSERT INTO public.countries VALUES ('PA', 'PAN', 'Панама', 'Панама', 'Panama', '591');
INSERT INTO public.countries VALUES ('PG', 'PNG', 'Папуа-Новая Гвинея', 'Папуа-Новая Гвинея', 'Papua New Guinea', '598');
INSERT INTO public.countries VALUES ('PY', 'PRY', 'Парагвай', 'Парагвай', 'Paraguay', '600');
INSERT INTO public.countries VALUES ('PE', 'PER', 'Перу', 'Перу', 'Peru', '604');
INSERT INTO public.countries VALUES ('PL', 'POL', 'Польша', 'Польша', 'Poland', '616');
INSERT INTO public.countries VALUES ('PT', 'PRT', 'Португалия', 'Португалия', 'Portugal', '620');
INSERT INTO public.countries VALUES ('PR', 'PRI', 'Пуэрто-Рико', 'Пуэрто-Рико', 'Puerto Rico', '630');
INSERT INTO public.countries VALUES ('MK', 'MKD', 'Македония', 'Македония', 'Macedonia', '807');
INSERT INTO public.countries VALUES ('RU', 'RUS', 'Россия', 'Россия', 'Russian Federation', '643');
INSERT INTO public.countries VALUES ('RW', 'RWA', 'Руанда', 'Руанда', 'Rwanda', '646');
INSERT INTO public.countries VALUES ('RO', 'ROU', 'Румыния', 'Румыния', 'Romania', '642');
INSERT INTO public.countries VALUES ('WS', 'WSM', 'Самоа', 'Самоа', 'Samoa', '882');
INSERT INTO public.countries VALUES ('SM', 'SMR', 'Сан-Марино', 'Сан-Марино', 'San Marino', '674');
INSERT INTO public.countries VALUES ('SA', 'SAU', 'Саудовская Аравия', 'Саудовская Аравия', 'Saudi Arabia', '682');
INSERT INTO public.countries VALUES ('SN', 'SEN', 'Сенегал', 'Сенегал', 'Senegal', '686');
INSERT INTO public.countries VALUES ('RS', 'SRB', 'Сербия', 'Сербия', 'Serbia', '688');
INSERT INTO public.countries VALUES ('SC', 'SYC', 'Сейшелы', 'Сейшелы', 'Seychelles', '690');
INSERT INTO public.countries VALUES ('SG', 'SGP', 'Сингапур', 'Сингапур', 'Singapore', '702');
INSERT INTO public.countries VALUES ('SY', 'SYR', 'Сирия', 'Сирия', 'Syria', '760');
INSERT INTO public.countries VALUES ('SK', 'SVK', 'Словакия', 'Словакия', 'Slovakia', '703');
INSERT INTO public.countries VALUES ('SI', 'SVN', 'Словения', 'Словения', 'Slovenia', '705');
INSERT INTO public.countries VALUES ('GB', 'GBR', 'Соединенное Королевство', 'Соединенное Королевство', 'United Kingdom', '826');
INSERT INTO public.countries VALUES ('US', 'USA', 'Соединенные Штаты', 'Соединенные Штаты', 'United States', '840');
INSERT INTO public.countries VALUES ('SO', 'SOM', 'Сомали', 'Сомали', 'Somalia', '706');
INSERT INTO public.countries VALUES ('SD', 'SDN', 'Судан', 'Судан', 'Sudan', '729');
INSERT INTO public.countries VALUES ('TJ', 'TJK', 'Таджикистан', 'Таджикистан', 'Tajikistan', '762');
INSERT INTO public.countries VALUES ('TH', 'THA', 'Таиланд', 'Таиланд', 'Thailand', '764');
INSERT INTO public.countries VALUES ('TW', 'TWN', 'Тайвань', 'Тайвань', 'Taiwan', '158');
INSERT INTO public.countries VALUES ('TZ', 'TZA', 'Танзания', 'Танзания', 'Tanzania', '834');
INSERT INTO public.countries VALUES ('TV', 'TUV', 'Тувалу', 'Тувалу', 'Tuvalu', '798');
INSERT INTO public.countries VALUES ('TN', 'TUN', 'Тунис', 'Тунис', 'Tunisia', '788');
INSERT INTO public.countries VALUES ('TM', 'TKM', 'Туркмения', 'Туркмения', 'Turkmenistan', '795');
INSERT INTO public.countries VALUES ('TR', 'TUR', 'Турция', 'Турция', 'Turkey', '792');
INSERT INTO public.countries VALUES ('UG', 'UGA', 'Уганда', 'Уганда', 'Uganda', '800');
INSERT INTO public.countries VALUES ('UZ', 'UZB', 'Узбекистан', 'Узбекистан', 'Uzbekistan', '860');
INSERT INTO public.countries VALUES ('UA', 'UKR', 'Украина', 'Украина', 'Ukraine', '804');
INSERT INTO public.countries VALUES ('UY', 'URY', 'Уругвай', 'Уругвай', 'Uruguay', '858');
INSERT INTO public.countries VALUES ('FO', 'FRO', 'Фарерские острова', 'Фарерские острова', 'Faroe Islands', '234');
INSERT INTO public.countries VALUES ('FJ', 'FJI', 'Фиджи', 'Фиджи', 'Fiji', '242');
INSERT INTO public.countries VALUES ('PH', 'PHL', 'Филиппины', 'Филиппины', 'Philippines', '608');
INSERT INTO public.countries VALUES ('FI', 'FIN', 'Финляндия', 'Финляндия', 'Finland', '246');
INSERT INTO public.countries VALUES ('FR', 'FRA', 'Франция', 'Франция', 'France', '250');
INSERT INTO public.countries VALUES ('HR', 'HRV', 'Хорватия', 'Хорватия', 'Croatia', '191');
INSERT INTO public.countries VALUES ('CF', 'CAF', 'Центрально-Африканская Республика', 'Центрально-Африканская Республика', 'Central African Republic', '140');
INSERT INTO public.countries VALUES ('ME', 'MNE', 'Черногория', 'Черногория', 'Montenegro', '499');
INSERT INTO public.countries VALUES ('CZ', 'CZE', 'Чешская Республика', 'Чешская Республика', 'Czech Republic', '203');
INSERT INTO public.countries VALUES ('CL', 'CHL', 'Чили', 'Чили', 'Chile', '152');
INSERT INTO public.countries VALUES ('CH', 'CHE', 'Швейцария', 'Швейцария', 'Switzerland', '756');
INSERT INTO public.countries VALUES ('SE', 'SWE', 'Швеция', 'Швеция', 'Sweden', '752');
INSERT INTO public.countries VALUES ('LK', 'LKA', 'Шри-Ланка', 'Шри-Ланка', 'Sri Lanka', '144');
INSERT INTO public.countries VALUES ('EC', 'ECU', 'Эквадор', 'Эквадор', 'Ecuador', '218');
INSERT INTO public.countries VALUES ('EE', 'EST', 'Эстония', 'Эстония', 'Estonia', '233');
INSERT INTO public.countries VALUES ('ET', 'ETH', 'Эфиопия', 'Эфиопия', 'Ethiopia', '231');
INSERT INTO public.countries VALUES ('ZA', 'ZAF', 'Южная Африка', 'Южная Африка', 'South Africa', '710');
INSERT INTO public.countries VALUES ('OS', 'OST', 'Южная Осетия', 'Южная Осетия', 'South Ossetia', '896');
INSERT INTO public.countries VALUES ('SS', 'SSD', 'Южный Судан', 'Южный Судан', 'South Sudan', '728');
INSERT INTO public.countries VALUES ('JM', 'JAM', 'Ямайка', 'Ямайка', 'Jamaica', '388');
INSERT INTO public.countries VALUES ('JP', 'JPN', 'Япония', 'Япония', 'Japan', '392');